-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.

hl.config({
  decoration = {
    fullscreen_opacity = 0.95,
    rounding_power = 1.05,
  },
})

